### PR TITLE
Addition of crucial "e"

### PR DESCRIPTION
**Pull request by codymikol**
I think this could be huge for your project, I see big things happening here.

### CODE REVIEW

**Comment by petertseng** [comment]
I'm afraid to merge it because I'm scared that https://dlang.org/ will be angry at me. maybe we could go for e instead?

**Comment by codymikol** [comment]
It was a very serious refactor, but I managed to make those changes. I may need to write some tests to verify this functionality...

**Comment by petertseng** [comment]
it's such a relief to see that the changes were possible to make. I was quite anxious about that.

Don't forget to edit the PR title so that it accurately reflects that we're adding `e` instead of `d`. We wouldn't want things to be inaccurate now!

**Comment by codymikol** [comment]
Great catch! It would definitely cause terrible confusion down the line. I've updated my title.

**Pull request merged**
